In [20]:
import pandas as pd

In [21]:
df_anime = pd.read_csv("anime.csv")

In [22]:
df_anime.shape

(12294, 7)

In [23]:
df_anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [24]:
df_anime.tail()

,anime_id,name,genre,type,episodes,rating,members
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [25]:
df_anime.sample(3)

,anime_id,name,genre,type,episodes,rating,members
181,9890,Major: Message,"Comedy, Drama, Sports",OVA,1,8.36,12282
9709,27843,Nemurenu Yoru no Chiisana Ohanashi,Kids,OVA,3,6.25,53
6523,23903,Tuzki: Love Assassin,"Comedy, Romance",ONA,1,6.08,309

In [26]:
df_anime.info()

<class 'pandas.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  str
 2   genre     12232 non-null  str
 3   type      12269 non-null  str
 4   episodes  12294 non-null  str
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 1.3 MB

In [27]:
df_anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [28]:
df_anime.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [29]:
df_anime.duplicated().sum()

np.int64(0)

In [30]:
df_anime.corr(numeric_only=True)['rating']

anime_id   -0.284625
rating      1.000000
members     0.387979
Name: rating, dtype: float64

In [31]:
df_rating = pd.read_csv("rating.csv")

In [32]:
df_rating.shape

(7813737, 3)

In [33]:
df_rating.sample(3)

         user_id  anime_id  rating
2287613    22026      5081       9
1245744    11755      8675       7
6199810    57951       584      10

In [34]:
df_rating.info()

<class 'pandas.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB

In [35]:
df_rating.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64

In [36]:
df_rating.describe()

            user_id      anime_id        rating
count  7.813737e+06  7.813737e+06  7.813737e+06
mean   3.672796e+04  8.909072e+03  6.144030e+00
std    2.099795e+04  8.883950e+03  3.727800e+00
min    1.000000e+00  1.000000e+00 -1.000000e+00
25%    1.897400e+04  1.240000e+03  6.000000e+00
50%    3.679100e+04  6.213000e+03  7.000000e+00
75%    5.475700e+04  1.409300e+04  9.000000e+00
max    7.351600e+04  3.451900e+04  1.000000e+01

In [37]:
df_rating.duplicated().sum()

np.int64(1)

In [38]:
df_rating.corr()

           user_id  anime_id    rating
user_id   1.000000 -0.031642  0.002467
anime_id -0.031642  1.000000 -0.005888
rating    0.002467 -0.005888  1.000000